name: hid_device_platform_interface
description: A common platform interface for the hid_device plugin.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  js_bindings: 0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
